const a = [{
  abilities: ["Overgrow"],
  weight: 15.2,
  weakness: ["Fire", "Psychic", "Flying", "Ice"],
  number: "0001",
  height: 28.0,
  name: "a",
  id: 2,
  type: ["grass", "poison"],
},
{
  abilities: ["Overgrow"],
  weight: 15.2,
  weakness: ["Fire", "Psychic", "Flying", "Ice"],
  number: "0001",
  height: 28.0,
  name: "b",
  id: 1,
  type: ["grass", "poison"],
},
{
  abilities: ["Overgrow"],
  weight: 15.2,
  weakness: ["Fire", "Psychic", "Flying", "Ice"],
  number: "0001",
  height: 28.0,
  name: "c",
  id: 3,
  type: ["grass", "poison"],
},
{
  abilities: ["Overgrow"],
  weight: 15.2,
  weakness: ["Fire", "Psychic", "Flying", "Ice"],
  number: "0001",
  height: 28.0,
  name: "d",
  id: 4,
  type: ["grass", "poison"],
},

]
const b = [
  {
    abilities: ["Overgrow"],
    weight: 15.2,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    number: "0001",
    height: 28.0,
    name: "b",
    id: 2,
    type: ["grass", "poison"],
  },
  {
    abilities: ["Overgrow"],
    weight: 15.2,
    weakness: ["Fire", "Psychic", "Flying", "Ice"],
    number: "0001",
    height: 28.0,
    name: "c",
    id: 3,
    type: ["grass", "poison"],
  },
]